### PR TITLE
Split out roadmaps

### PR DESCRIPTION
**Pull request by joebochill**
For PXBLUE-1842

#### Changes proposed in this Pull Request:
- Split roadmaps so a RX file only contains items from Release X
- Update build script to build all roadmaps
- Add placeholders for R20/21
- Add variable for current year and quarter to make it easier to identify things to remove / ensure everything is only from the current release

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
What's the reason that we list out those roadmap objects by "year" and "quarter", instead of just "release", like R19, R18, ...?

**Comment by joebochill** [comment]
> What's the reason that we list out those roadmap objects by "year" and "quarter", instead of just "release", like R19, R18, ...?

At this point, it's just legacy. I think at one point we had a year and quarter dropdown on doc-it. We could probably refactor them out at some point if we want to.

I don't mind having the extra info, although it may be better to do something like year/month instead of year/quarter in case we start doing releases more frequently than every quarter.

**Comment by joebochill** [comment]
Logged https://github.com/pxblue/doc-it/issues/374 for future enhancements to the structure of the files

**Review by huayunh — APPROVED** [review]
Functionality-wise looks good. 

For future updates, I suppose that for the empty buckets (objects with `"items": []`), we don't really need to include them in old releases. Or maybe we can split buckets out to its own files... idk.

**Comment by joebochill** [comment]
I left the empty buckets to keep a consistent set of buckets/descriptions, but agree with you that we could probably separate them out into a shared resource. If you want to add that as a comment on the linked enhancement we can make sure not to forget.

**Pull request merged**
