### PR TITLE
Update for R18 Sprint 2

### PR DESCRIPTION
**Pull request by huayunh**
#### Changes proposed in this Pull Request:
- Update for R18 Sprint 2
- Marking a few things to be inner sourced

### CODE REVIEW

**Review by joebochill — COMMENTED** [review]
How are we deciding what is "Innersource" and what is "PX Blue" on the Figma stuff?

**Comment by joebochill** [comment]
Yeah, I'm never quite sure how to account for KH

**Review by joebochill — APPROVED** [review]

**Comment by huayunh** [comment]
There are two KH's on the team :P

**Comment by joebochill** [comment]
Oh right 🤷

**Pull request merged**
