### PR TITLE
Add initial content for R19

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Add initial outline for R19 and R20 content

#### Screenshots:
MicrosoftTeams-image
MicrosoftTeams-image (1)
MicrosoftTeams-image (2)

R20:
image

### CODE REVIEW

**Comment by joebochill** [comment]
@emclaug2 for some reason, it's not letting me add you as a reviewer...you aren't in the list. Not sure what's up with that.

**Comment by emclaug2** [comment]
This is so weird; I can't even add myself as a reviewer.   I don't think anything has changed with my account (at least to my knowledge).

**Comment by huayunh** [comment]
That reviewer issue happened to me in another PR, but it was me unable to add Joe

**Comment by emclaug2** [comment]
> That reviewer issue happened to me in another PR, but it was me unable to add Joe

That makes me feel better 👍

**Comment by huayunh** [comment]
RN Collapsible App Bar — what's the difference between that and what we currently have in the header component? Is it just changing from on tap to on scroll?

**Review by huayunh — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]
looks good

**Comment by joebochill** [comment]
> Or maybe have like a "scroll percentage" thing exposed as part of the API? :P

Hmm, potentially yeah. I hadn't thought of that approach - it could work

**Pull request merged**
